CREATE TABLE VENDOR (
    VENDORID        VARCHAR(6) PRIMARY KEY NOT NULL,
    VENDORNAME      VARCHAR(15) NOT NULL,
    ADDRESS1        VARCHAR(15),
    ADDRESS2        VARCHAR(15),
    ADDRESS3        VARCHAR(15),
    CITY            VARCHAR(15),
    STATE           BOOLEAN,
    PIN             VARCHAR(8),
    COUNTRY         VARCHAR(15),
    CONTACTNO1      INTEGER NOT NULL,
    CONTACTNO2      INTEGER,
    VENDORLOGO      BLOB,
    GST             VARCHAR(20) NOT NULL,
    IEC             VARCHAR(20),
    PANNO           VARCHAR(10),
    VENDORINVTEMPL  BLOB,
    STATUS          BOOLEAN DEFAULT TRUE
);


CREATE TABLE VENDOR_PRODUCTS (
    ID              INTEGER PRIMARY KEY,
    VENDORID        VARCHAR(6) NOT NULL,
    PRODUCTID       VARCHAR(6) NOT NULL,
    BATCHNO         VARCHAR(10),
    STATUS          BOOLEAN DEFAULT TRUE
);

CREATE TABLE PRODUCTS_MAIN (
    ID              INTEGER PRIMARY KEY,
    PRODUCTID       VARCHAR(6) NOT NULL,
    PRODUCTDESC     VARCHAR(15) NOT NULL,
    PRODUCTPRICE    INTEGER,
    BATCHNO         VARCHAR(10),
    CAPACITY        INTEGER,
    PPM             INTEGER,
    STATUS          BOOLEAN DEFAULT TRUE
);


CREATE TABLE CUSTOMERS_MASTER (
    VENDORID        VARCHAR(6) UNIQUE NOT NULL,
    CUSTID          VARCHAR(6) UNIQUE NOT NULL,
    CUSTNAME        VARCHAR(15) NOT NULL,
    ADDRESS1        VARCHAR(15),
    ADDRESS2        VARCHAR(15),
    ADDRESS3        VARCHAR(15),
    CITY            VARCHAR(15),
    STATE           VARCHAR(15),
    PIN             VARCHAR(8),
    COUNTRY         VARCHAR(15),
    CONTACTNO1      INTEGER NOT NULL,
    CONTACTNO2      INTEGER NOT NULL,
    STATUS          BOOLEAN DEFAULT TRUE
);

CREATE TABLE NOTIFICATION_MASTER (
    NOTIFICATIONID   INTEGER PRIMARY KEY NOT NULL,
    NOTIFICATIONTYPE VARCHAR(7) CHECK (NOTIFICATIONTYPE IN ('SMS', 'EmailID')),
    NOTIFICATIONTEMPL VARCHAR(100),
    STATUS           BOOLEAN DEFAULT TRUE
);



CREATE TABLE CUSTOMER_INSTALLATIONS (
    ID                   INTEGER PRIMARY KEY,
    VENDORID             VARCHAR(6) NOT NULL,
    INVOICENO            VARCHAR(10) NOT NULL,
    DEVICEID             INTEGER NOT NULL,
    INSTALLATION_LOC     VARCHAR(20),
    INSTALLATION_DATE    DATE,
    CONSUMPTION          INTEGER NOT NULL,
    PPM                  INTEGER NOT NULL,
    CONTACTNO1           INTEGER,
    CONTACTNO2           INTEGER,
    
    CONSTRAINT FK_VENDOR FOREIGN KEY (VENDORID) REFERENCES CUSTOMERS_MASTER (CUSTID),
    CONSTRAINT FK_INVOICE FOREIGN KEY (INVOICENO) REFERENCES SALES_TRANSACTION (INVOICENO)
);

CREATE TABLE SALES_TRANSACTION (
    VENDORID       VARCHAR(6) NOT NULL,
    INVOICENO      VARCHAR(10) PRIMARY KEY NOT NULL,
    PRODUCTID      VARCHAR(6) NOT NULL,
    QUANTITY       INTEGER,
    BATCHNO        VARCHAR(10),
    PRICE          INTEGER NOT NULL,
    TOTAL          INTEGER NOT NULL,
    STATUS         BOOLEAN DEFAULT TRUE,
    CONSTRAINT FK_VENDOR FOREIGN KEY (VENDORID) REFERENCES CUSTOMERS_MASTER (CUSTID) -- Replace CUSTOMERS_MASTER with the actual table name if different
);